Basics with np

In [ ]:
# !pip3 install torch torchvision torchaudio

     |████████████████████████████████| 2.9 MB 10.2 MB/s 
     |████████████████████████████████| 1.9 MB 43.0 MB/s 
You should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.


In [ ]:
!pip install numpy

You should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.


In [ ]:
import numpy as np
import torch
from torch.autograd import Variable

In [ ]:
np_data = np.arange(6).reshape((2,3))
np_data.shape
torch_data = torch.from_numpy(np_data)
torch_data.numpy()

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print(f'''
            abs 
            np{np.abs(data)} 
            torch{torch.abs(tensor)}
''')

print(
    f'''
            sine 
            np{np.sin(data)}
            torch{torch.sin(tensor)}
    '''
)


            abs 
            np[1 2 1 2] 
            torchtensor([1., 2., 1., 2.])


            sine 
            np[-0.84147098 -0.90929743  0.84147098  0.90929743]
            torchtensor([-0.8415, -0.9093,  0.8415,  0.9093])
    


In [ ]:
data = [[1,2], [3,4]]
nparray = np.array(data)
tensor = torch.Tensor(data)

print(f'''
        multiplication
{np.matmul(nparray, nparray)}
{torch.mm(tensor, tensor)}
''')

print(f'''
    dotmul
{nparray.dot(nparray)}
''')


        multiplication
[[ 7 10]
 [15 22]]
tensor([[ 7., 10.],
        [15., 22.]])


    dotmul
[[ 7 10]
 [15 22]]



In [ ]:
tensor = torch.FloatTensor([[1,2], [3,4]])
variable = Variable(tensor1, requires_grad=True)

print(tensor1, variable)

t_mean = torch.mean(tensor*tensor)
v_mean = torch.mean(variable*variable)

print(t_mean, v_mean)

tensor([[1., 2.],
        [3., 4.]]) tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor(7.5000) tensor(7.5000, grad_fn=<MeanBackward0>)


In [ ]:
v_mean.backward()

In [ ]:
print(variable.grad)
print(variable)
print(variable.data)
print(variable.data.numpy())

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a1f95f9a-05f9-4b52-8dcf-a3cd25f230bb' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>