In [2]:
import numpy as np
print(np.__version__)

### Basic Array Methods

In [10]:
a = np.array([[1.3,4.6,5],
              [2,3,7],
             ])
b = np.array([[2,6,5],
              [1,4,5]])
c = a+b
print(c)

[[ 3.3 10.6 10. ]
 [ 3.   7.  12. ]]


In [27]:
a.shape

(2, 3)

In [28]:
a.dtype

dtype('float64')

In [29]:
a.size

6

In [30]:
a.itemsize

8

In [33]:
a.itemsize * a.size

48

In [34]:
a.nbytes

48

### Array Acccss 

In [36]:
d = np.array([[1,2,3],
              [4,5,6]])

In [38]:
d[1,1]

5

In [39]:
d[1:]

array([[4, 5, 6]])

In [40]:
d[:1]

array([[1, 2, 3]])

In [49]:
d3 = np.array([[[1,2,3],
               [5,6,7],
               [8,9,1]],
              [[1,2,3],
               [5,6,7],
               [8,9,1]],]
             )

In [50]:
d3.shape

(2, 3, 3)

In [58]:
d3[1,2]

array([8, 9, 1])

In [62]:
d3[1,1,1]

6

In [63]:
d3[1,2,::-1]

array([1, 9, 8])

In [61]:
d3[1,::-1]

array([[8, 9, 1],
       [5, 6, 7],
       [1, 2, 3]])

### Some Different Array Initializers

In [65]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [71]:
np.full((3,3,3), 44)

array([[[44, 44, 44],
        [44, 44, 44],
        [44, 44, 44]],

       [[44, 44, 44],
        [44, 44, 44],
        [44, 44, 44]],

       [[44, 44, 44],
        [44, 44, 44],
        [44, 44, 44]]])

In [77]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
np.full_like(d3, 50)

array([[[50, 50, 50],
        [50, 50, 50],
        [50, 50, 50]],

       [[50, 50, 50],
        [50, 50, 50],
        [50, 50, 50]]])

In [83]:
np.random.rand(3,3)

array([[0.59617933, 0.24478605, 0.6551329 ],
       [0.5162084 , 0.67665238, 0.26762853],
       [0.09209564, 0.02236646, 0.69914227]])

In [99]:
np.random.seed(0)
randa = np.random.rand(3,3)

In [100]:
np.random.rand(3,3)
randb = np.random.rand(3,3)

In [101]:
print(randa) 
print(randb)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
[[0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329]]


In [106]:
np.random.randint(-10,20, size=(2,4))
# first two arguments denotes range of random values to be generated

array([[-3, -1, 15, -7],
       [-4, 13,  1,  4]])

### Math Operations


In [111]:
e = np.random.randint(1,30, size=(2,2,2))
print(e)

[[[ 4 13]
  [ 5 21]]

 [[ 9 15]
  [16 21]]]


In [112]:
f = np.random.randint(1,50, size=(2,2,2))

In [121]:
print(f)

[[[36 24]
  [16 14]]

 [[22 49]
  [ 6 42]]]


In [122]:
e ** 2

array([[[ 16, 169],
        [ 25, 441]],

       [[ 81, 225],
        [256, 441]]])

In [123]:
e + f

array([[[40, 37],
        [21, 35]],

       [[31, 64],
        [22, 63]]])

In [124]:
e - f

array([[[-32, -11],
        [-11,   7]],

       [[-13, -34],
        [ 10, -21]]])

In [125]:
e * f

array([[[144, 312],
        [ 80, 294]],

       [[198, 735],
        [ 96, 882]]])

In [126]:
e // f

array([[[0, 0],
        [0, 1]],

       [[0, 0],
        [2, 0]]])

In [127]:
e / f

array([[[0.11111111, 0.54166667],
        [0.3125    , 1.5       ]],

       [[0.40909091, 0.30612245],
        [2.66666667, 0.5       ]]])

In [128]:
np.matmul(e,f)

array([[[ 352,  278],
        [ 516,  414]],

       [[ 288, 1071],
        [ 478, 1666]]])

In [129]:
np.dot(e,f)

array([[[[ 352,  278],
         [ 166,  742]],

        [[ 516,  414],
         [ 236, 1127]]],


       [[[ 564,  426],
         [ 288, 1071]],

        [[ 912,  678],
         [ 478, 1666]]]])

In [143]:
print(e)
np.min(e, axis=0)


[[[ 4 13]
  [ 5 21]]

 [[ 9 15]
  [16 21]]]


array([[ 4, 13],
       [ 5, 21]])

In [131]:
np.max(e)

21

In [142]:
np.sum(e, axis=0)

array([[13, 28],
       [21, 42]])

In [147]:
g = np.zeros((2,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]]


In [148]:
h = np.ones((2,3))
print(h)

[[1. 1. 1.]
 [1. 1. 1.]]


In [150]:
np.hstack((g,h))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [151]:
np.vstack((g,h))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [154]:
np.reshape(h,(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])